### ISSUE TITLE
Repo conflict with open-data-api

### ISSUE THREAD

**Issue by dhammikamare** [CodeLanka/common-data-sri-lanka#3]
I think this datasets should be moved to https://github.com/CodeLanka/open-data-api as both projects have common goal. :+1:

**Comment by pasindud** [comment]
Not exactly common data is  about JSON for developers to do validation and other stuff, open data is about open data from ICTA

**Comment by ishan-marikar** [comment]
As explained above, common-data is/are basic data-sets that assist the developer with data that is already publicly available and well known, but not in a format that the computer in which the computer can easily parse it, for example, telephone area codes of Sri Lanka . Open-Data serves a different purpose. It is for the purposes of data-mining and research.

**Comment by dhammikamare** [comment]
noted :+1:
